#!/usr/bin/env python3
"""pb.py - PutnamBench harness for the curric lean solver.

One shared lake project (`../lean4`, with Mathlib already built) serves all
672 problems. Each run gets its own bench directory holding exactly ONE .lean
file, so an agent working from that directory cannot see or edit its
neighbours. Verification elaborates the single file with `lake env lean`
against the shared project -- no per-problem lake project, no re-fetch of
Mathlib.

Commands
    prepare                       build manifest.json from the pristine sources
    list [filters]                list problem names
    show <problem>                print manifest entry
    stage <problem> --dest DIR    create a bench directory
    verify --bench DIR            pass/fail one bench directory
    selftest                      check the checker against a synthetic problem

Work queue (see the "work queue" section below; used by run_putnam_solver.py)
    queue-init [filters]          create/extend problems.tsv
    claim --owner NAME            atomically take one todo row
    release <problem> --status S  record the outcome
    reap                          return abandoned claims to todo
    queue-status [-v]             counts, and optionally every row

Variants
    wsolution   the reference answer is inlined into the statement; the agent
                only writes a proof. This is what the leaderboard reports.
    full        the `abbrev <name>_solution := sorry` is left in place; the
                agent must produce the answer AND the proof.
Problems with no `abbrev` are identical under both variants.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent                    # putnambench/
LEAN4 = ROOT / "lean4"                # the shared lake project
SRC = LEAN4 / "src"                   # pristine statements (never modified)
WSOL = LEAN4 / "solutions_replaced_new"   # generated by rewrite_solutions.py
INFORMAL = ROOT / "informal" / "putnam.json"
MANIFEST = HERE / "manifest.json"

ALLOWED_AXIOMS = {"propext", "Classical.choice", "Quot.sound"}

# Textual escape hatches. `sorry` is handled separately (better message).
FORBIDDEN = [
    (r"\bsorryAx\b", "sorryAx"),
    (r"^\s*axiom\s", "axiom declaration"),
    (r"\bnative_decide\b", "native_decide"),
    (r"@\[\s*implemented_by", "@[implemented_by]"),
    (r"@\[\s*extern", "@[extern]"),
]

LEAN_TIMEOUT = int(os.environ.get("PB_LEAN_TIMEOUT", "1800"))


# --------------------------------------------------------------------------
# text utilities
# --------------------------------------------------------------------------

def strip_comments(text: str) -> str:
    """Remove -- line comments and (nesting-aware) /- -/ block comments.

    Docstrings (/-- -/) are block comments and go too; every frozen signature
    starts at the `theorem`/`abbrev` keyword, so nothing we compare is lost.
    """
    out = []
    i, n, depth = 0, len(text), 0
    while i < n:
        if text.startswith("/-", i):
            depth += 1
            i += 2
        elif text.startswith("-/", i) and depth:
            depth -= 1
            i += 2
        elif depth:
            i += 1
        elif text.startswith("--", i):
            j = text.find("\n", i)
            i = n if j < 0 else j
        else:
            out.append(text[i])
            i += 1
    return "".join(out)


def normalize(text: str) -> str:
    """Comment-free, whitespace-collapsed form used for signature matching."""
    return re.sub(r"\s+", " ", strip_comments(text)).strip()


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


# --------------------------------------------------------------------------- #
# shadowing guard
#
# The signature check above is TEXTUAL, so it cannot see a proof that leaves the
# statement byte-identical while redefining what a name in it MEANS. Caught in
# formalbench (minif2f__imo_2006_p3):
#
#     namespace imo_2006_p3
#     def IsLeast (s : Set ℝ) (a : ℝ) : Prop := a ∈ s
#
# Mathlib's `IsLeast s a` also requires `a` to be a lower bound, so dropping that
# conjunct throws away the whole problem -- and the file still elaborates, has no
# `sorry`, and depends on no extra axioms. Deliberately duplicated from
# formalbench/harness/fb.py rather than imported: this file is the verifier for a
# running fleet and must not break if that directory moves.
# --------------------------------------------------------------------------- #

DEFINES_RE = re.compile(
    r"^\s*(?:@\[[^\]]*\]\s*)?(?:noncomputable\s+|private\s+|protected\s+|scoped\s+|local\s+)*"
    r"(def|abbrev|structure|inductive|class|instance|notation|macro|syntax)\s+"
    r"([A-Za-z_][A-Za-z0-9_'.]*)", re.MULTILINE)

IDENT_RE = re.compile(r"[A-Za-z_][A-Za-z0-9_'.]*")


def defined_names(text: str) -> set:
    """Global names a file declares (last component only: `Complex.abs` -> `abs`)."""
    return {n.split(".")[-1] for _, n in DEFINES_RE.findall(strip_comments(text))}


def sig_binders(sig: str) -> set:
    """Names BOUND inside the statement -- binders, not globals.

    `theorem t : ∃ f : ℕ → ℕ, ...` binds `f`, so a helper `def f` beside the
    theorem shadows nothing. Without this every such helper is a false positive.
    """
    out = set()
    for grp in re.findall(r"[({\[⦃]\s*([^:()\[\]{}⦃⦄]+?)\s*:", sig):
        out.update(IDENT_RE.findall(grp))
    for grp in re.findall(r"[∀∃]\s*([^,:]+)[,:]", sig):
        out.update(IDENT_RE.findall(grp))
    for grp in re.findall(r"\bfun\s+([^=]+?)(?:=>|↦)", sig):
        out.update(IDENT_RE.findall(grp))
    return out


def shadowing(text: str, sig: str, thm: str, provided: set) -> list:
    """Names `text` redefines that also occur free in the frozen statement."""
    allowed = set(provided) | {thm}
    bound = sig_binders(sig)
    sig_idents = {t.split(".")[-1] for t in IDENT_RE.findall(sig)}
    return sorted(n for n in defined_names(text)
                  if n in sig_idents and n not in bound and n not in allowed
                  and not n.endswith("_solution"))


def extract_theorem_sig(text: str, name: str) -> str:
    """`theorem <name> ... :=` with the proof removed, normalized.

    Statement-internal `:=` (from `let`, structure instances) all precede the
    one that introduces the proof, so taking the last is correct on pristine
    sources, where the proof is exactly `sorry`.
    """
    body = strip_comments(text)
    m = re.search(r"\btheorem\s+" + re.escape(name) + r"\b", body)
    if not m:
        raise ValueError(f"no `theorem {name}` in source")
    tail = body[m.start():]
    cut = tail.rfind(":=")
    if cut < 0:
        raise ValueError(f"no `:=` after `theorem {name}`")
    return normalize(tail[: cut + 2])


def extract_abbrev(text: str) -> tuple[str, str, str, str] | None:
    """(sig, name, type, reference answer) for a factored-solution problem."""
    for m in re.finditer(
        r"^(?:noncomputable\s+)?abbrev\s+(\S+)\s*:\s*(.*?):=\s*sorry\s*$",
        text,
        re.MULTILINE,
    ):
        name, typ = m.group(1), m.group(2).strip()
        rest = text[m.end():].lstrip("\n")
        answer = ""
        if rest.startswith("--"):
            answer = rest.split("\n", 1)[0][2:].strip()
        return normalize(m.group(0)[: m.group(0).rfind(":=") + 2]), name, typ, answer
    return None


# --------------------------------------------------------------------------
# prepare
# --------------------------------------------------------------------------

def cmd_prepare(args) -> int:
    if not SRC.is_dir():
        sys.exit(f"missing {SRC}")

    # Generate the wsolution variant with the upstream script, so our inlining
    # matches what everyone else reports against.
    script = LEAN4 / "scripts" / "rewrite_solutions.py"
    print(f"running {script.relative_to(ROOT)} ...")
    r = subprocess.run([sys.executable, str(script)], cwd=LEAN4,
                       capture_output=True, text=True)
    if r.returncode != 0:
        print(r.stdout[-2000:], r.stderr[-2000:], file=sys.stderr)
        sys.exit("rewrite_solutions.py failed")
    print(f"  wrote {len(list(WSOL.glob('*.lean')))} files to "
          f"{WSOL.relative_to(ROOT)}")

    informal = {e["problem_name"]: e for e in json.loads(INFORMAL.read_text())}

    entries, skipped = {}, []
    for f in sorted(SRC.glob("*.lean")):
        name = f.stem
        text = f.read_text(encoding="utf8")
        try:
            sig = extract_theorem_sig(text, name)
        except ValueError as e:
            skipped.append(f"{name}: {e}")
            continue

        ab = extract_abbrev(text)
        wfile = WSOL / f"{name}_sol.lean"
        sig_w = None
        if wfile.exists():
            try:
                sig_w = extract_theorem_sig(
                    wfile.read_text(encoding="utf8"), name)
            except ValueError as e:
                skipped.append(f"{name} (wsolution): {e}")

        inf = informal.get(name, {})
        m = re.match(r"putnam_(\d{4})_([ab]\d+)$", name)
        entries[name] = {
            "name": name,
            "year": int(m.group(1)) if m else None,
            "index": m.group(2) if m else None,
            "tags": inf.get("tags", []),
            "informal_statement": inf.get("informal_statement", ""),
            "informal_solution": inf.get("informal_solution", "None."),
            "has_solution": ab is not None,
            "solution_name": ab[1] if ab else None,
            "solution_type": ab[2] if ab else None,
            "solution_sig": ab[0] if ab else None,
            "reference_answer": ab[3] if ab else None,
            "sig": sig,
            "sig_wsolution": sig_w,
            "src_sha256": sha256(f),
        }

    manifest_path().write_text(json.dumps(entries, indent=1, ensure_ascii=False))
    n_sol = sum(1 for e in entries.values() if e["has_solution"])
    print(f"manifest: {len(entries)} problems ({n_sol} with a factored answer)"
          f" -> {MANIFEST.relative_to(ROOT)}")
    if skipped:
        print(f"skipped {len(skipped)}:", file=sys.stderr)
        for s in skipped[:20]:
            print("  " + s, file=sys.stderr)
    return 0


def manifest_path() -> Path:
    """The manifest, overridable via PB_MANIFEST (used by `selftest`)."""
    return Path(os.environ.get("PB_MANIFEST", MANIFEST))


def load_manifest() -> dict:
    p = manifest_path()
    if not p.exists():
        sys.exit(f"no {p.name} - run `pb.py prepare` first")
    return json.loads(p.read_text())


# --------------------------------------------------------------------------
# list / show
# --------------------------------------------------------------------------

def cmd_list(args) -> int:
    man = load_manifest()
    for name, e in sorted(man.items()):
        if args.year and e["year"] != args.year:
            continue
        if args.tag and args.tag not in e["tags"]:
            continue
        if args.with_answer and not e["has_solution"]:
            continue
        if args.no_answer and e["has_solution"]:
            continue
        if args.verbose:
            print(f"{name:24s} {'ANS' if e['has_solution'] else '   '} "
                  f"{','.join(e['tags'])}")
        else:
            print(name)
    return 0


def cmd_show(args) -> int:
    man = load_manifest()
    if args.problem not in man:
        sys.exit(f"unknown problem: {args.problem}")
    print(json.dumps(man[args.problem], indent=2, ensure_ascii=False))
    return 0


# --------------------------------------------------------------------------
# stage
# --------------------------------------------------------------------------

VERIFY_SH = """#!/usr/bin/env bash
# Pass/fail for one PutnamBench problem. Run from the benchmark directory.
set -uo pipefail
cd "$(dirname "$0")"
export PATH="$HOME/.elan/bin:$PATH"
exec python3 {pb} verify --bench "$PWD"
"""

README_MD = """# {name}

{tags}

## Problem

{informal}

## Task

`{name}.lean` contains a single Lean 4 theorem whose proof is `sorry`.
Replace the `sorry` with a real proof. {answer_task}

Mathlib is already built. To elaborate your file without the full check:

```bash
(cd {lean4} && lake env lean {dest}/{name}.lean)
```

Or just run `./verify.sh`, which does that and more.

## Rules

- Work ONLY inside this directory. Do not read, write, or reference any other
  benchmark directory, and do not modify anything under `{lean4}` -- that is
  the shared Mathlib project every other run uses.
- Do NOT change the theorem statement. `verify.sh` compares the statement
  against a frozen signature and fails if a hypothesis, binder or conclusion
  was altered, renamed or dropped.{answer_rule}
- No `sorry`, no `axiom`, no `native_decide`, no `@[implemented_by]`, no
  `@[extern]`. The only axioms your proof may depend on are `propext`,
  `Classical.choice` and `Quot.sound` (the Mathlib standard three).
- Helper lemmas above the theorem are fine, as long as they obey the rules.

`verify.sh` prints `PASS [{name}]` when the problem is solved.
"""


def cmd_stage(args) -> int:
    man = load_manifest()
    name = args.problem
    if name not in man:
        sys.exit(f"unknown problem: {name}")
    e = man[name]

    if args.variant == "wsolution":
        src = WSOL / f"{name}_sol.lean"
        if not src.exists():
            sys.exit(f"no wsolution source for {name} - run `pb.py prepare`")
    else:
        src = SRC / f"{name}.lean"

    dest = Path(args.dest).resolve()
    if dest.exists() and not args.force:
        sys.exit(f"{dest} exists (use --force)")
    dest.mkdir(parents=True, exist_ok=True)

    # The pristine sources carry the reference answer as a comment right under
    # the `abbrev` (and rewrite_solutions.py leaves that comment behind). Under
    # the `full` variant that comment IS the task, so strip it either way.
    text = src.read_text(encoding="utf8")
    if e["has_solution"] and e["reference_answer"]:
        ref = e["reference_answer"].strip()
        text = "".join(
            ln for ln in text.splitlines(keepends=True)
            if ln.strip().lstrip("-").strip() != ref)
    (dest / f"{name}.lean").write_text(text, encoding="utf8")

    vs = dest / "verify.sh"
    vs.write_text(VERIFY_SH.format(pb=HERE / "pb.py"))
    vs.chmod(0o755)

    if args.variant == "full" and e["has_solution"]:
        answer_task = (
            f"\n\nThis problem also has a factored answer: the "
            f"`abbrev {e['solution_name']}` at the top is `sorry` too. You "
            f"must supply the correct closed-form answer there AND prove the "
            f"theorem with it.")
        answer_rule = (
            f"\n- Do NOT change the type of `{e['solution_name']}`; it is "
            f"frozen the same way. Supply a value, not a `sorry`.")
    else:
        answer_task = "The answer, where the problem asks for one, is already inlined."
        answer_rule = ""

    (dest / "README.md").write_text(README_MD.format(
        name=name,
        tags=" ".join(f"`{t}`" for t in e["tags"]) or "(untagged)",
        informal=e["informal_statement"],
        lean4=LEAN4,
        dest=dest,
        answer_task=answer_task,
        answer_rule=answer_rule,
    ))

    (dest / ".pb.json").write_text(json.dumps(
        {"problem": name, "variant": args.variant}, indent=1))

    print(f"staged {name} ({args.variant}) -> {dest}")
    return 0


# --------------------------------------------------------------------------
# verify
# --------------------------------------------------------------------------

def fail(bench: str, msg: str) -> int:
    print(f"FAIL [{bench}] {msg}")
    return 1


def cmd_verify(args) -> int:
    bench = Path(args.bench).resolve()
    cfg_path = bench / ".pb.json"
    if not cfg_path.exists():
        sys.exit(f"{bench} is not a staged bench directory (no .pb.json)")
    cfg = json.loads(cfg_path.read_text())
    name, variant = cfg["problem"], cfg["variant"]
    man = load_manifest()
    e = man[name]

    f = bench / f"{name}.lean"
    if not f.exists():
        return fail(name, f"{name}.lean is missing")
    text = f.read_text(encoding="utf8")
    body = strip_comments(text)

    # ---- 1. textual escape hatches ---------------------------------------
    if re.search(r"\bsorry\b", body):
        return fail(name, "a 'sorry' remains")
    for pat, what in FORBIDDEN:
        if re.search(pat, body, re.MULTILINE):
            return fail(name, f"forbidden escape hatch ({what})")
    bad = [i for i in re.findall(r"^\s*import\s+(\S+)", body, re.MULTILINE)
           if i != "Mathlib"]
    if bad:
        return fail(name, f"unexpected import(s): {', '.join(bad)}")

    # ---- 2. the statement still says what it said ------------------------
    norm = normalize(text)
    sig = e["sig_wsolution"] if variant == "wsolution" else e["sig"]
    if sig is None:
        return fail(name, "no frozen signature for this variant")
    if sig not in norm:
        return fail(name, "the theorem statement was altered "
                          "(frozen signature not found)")

    # 2b. the statement's WORDS are unchanged; check its MEANING is too.
    #     Anything the pristine problem file already declared is part of the
    #     problem, not a rewrite of it.
    pristine = (WSOL / f"{name}_sol.lean" if variant == "wsolution"
                else SRC / f"{name}.lean")
    provided = (defined_names(pristine.read_text(encoding="utf8"))
                if pristine.exists() else set())
    shad = shadowing(text, sig, name, provided)
    if shad:
        return fail(name, "the proof redefines "
                          f"{', '.join(repr(s) for s in shad)}, which the frozen "
                          "statement depends on. The statement must keep its "
                          "Mathlib meaning -- do not shadow names it uses.")
    if variant == "full" and e["has_solution"]:
        if e["solution_sig"] not in norm:
            return fail(name, f"the type of {e['solution_name']} was altered")

    # ---- 3. it elaborates -------------------------------------------------
    names = [name]
    if variant == "full" and e["has_solution"]:
        names.append(e["solution_name"])
    check = bench / ".pb_check.lean"
    check.write_text(text.rstrip() + "\n\n"
                     + "".join(f"#print axioms {n}\n" for n in names))
    try:
        r = subprocess.run(
            ["lake", "env", "lean", str(check)],
            cwd=LEAN4, capture_output=True, text=True, timeout=LEAN_TIMEOUT)
    except subprocess.TimeoutExpired:
        check.unlink(missing_ok=True)
        return fail(name, f"lean timed out after {LEAN_TIMEOUT}s")
    out = (r.stdout or "") + (r.stderr or "")
    check.unlink(missing_ok=True)

    if r.returncode != 0 or re.search(r"^.*: error:", out, re.MULTILINE):
        print(out[-4000:])
        return fail(name, "the file does not elaborate")
    if "declaration uses 'sorry'" in out:
        return fail(name, "a declaration uses 'sorry'")

    # ---- 4. clean axioms --------------------------------------------------
    for n in names:
        m = re.search(r"'" + re.escape(n) + r"' depends on axioms: \[(.*?)\]",
                      out, re.DOTALL)
        if not m:
            if f"'{n}' does not depend on any axioms" in out:
                continue
            return fail(name, f"could not read `#print axioms {n}`")
        for ax in (a.strip() for a in m.group(1).split(",")):
            if ax and ax not in ALLOWED_AXIOMS:
                return fail(name, f"{n} depends on '{ax}'")

    print(f"PASS [{name}]")
    return 0


# --------------------------------------------------------------------------
# work queue
#
# One human-readable TSV, one row per problem. Every mutation takes an
# exclusive flock on a sidecar lock file and rewrites the table atomically
# (temp + os.replace), so any number of runners on this host can claim from
# it concurrently without stepping on each other. Rows are only ever mutated
# under that lock; readers (`queue-status`) take a shared lock.
#
# A runner that dies without releasing leaves its row `running`. `reap` puts
# such rows back to `todo` once the owning pid is gone or the claim is older
# than --stale-seconds -- the same failure we hit with the orphaned eolymp
# solver, handled here rather than left to a human.
# --------------------------------------------------------------------------

QUEUE = HERE / "problems.tsv"
QUEUE_COLS = ["problem", "variant", "status", "owner", "pid",
              "claimed_at", "finished_at", "steps", "note"]
STATUSES = {"todo", "running", "solved", "failed", "timeout", "skip",
            # The solver filed a Lean proof that the frozen statement is
            # FALSE. Terminal, but deliberately not "solved": nothing here
            # has checked the claim. A human reviews the artifacts under
            # putnambench/defects/ and then moves the row to skip (defect
            # confirmed) or todo (claim rejected).
            "disproved"}
# Only used for rows we CANNOT check by pid (no pid recorded, or a corrupt
# timestamp). A live worker is never reaped on age alone -- Lean runs are
# expected to last days, so an age-based steal would kill real work. Kept
# well beyond the solver's own per-problem timeout as a last-resort floor.
STALE_SECONDS = 5 * 24 * 3600


def queue_path() -> Path:
    return Path(os.environ.get("PB_QUEUE", QUEUE))


class _Lock:
    """flock on a sidecar; `shared=True` for readers."""

    def __init__(self, shared: bool = False):
        self.shared = shared
        self.fh = None

    def __enter__(self):
        import fcntl
        p = queue_path().with_suffix(queue_path().suffix + ".lock")
        p.parent.mkdir(parents=True, exist_ok=True)
        self.fh = open(p, "a+")
        fcntl.flock(self.fh,
                    fcntl.LOCK_SH if self.shared else fcntl.LOCK_EX)
        return self

    def __exit__(self, *exc):
        import fcntl
        fcntl.flock(self.fh, fcntl.LOCK_UN)
        self.fh.close()
        return False


def _now() -> str:
    import datetime
    return datetime.datetime.now(datetime.timezone.utc).isoformat(
        timespec="seconds")


def _read_rows() -> list[dict]:
    p = queue_path()
    if not p.exists():
        return []
    rows = []
    for i, line in enumerate(p.read_text().splitlines()):
        if not line.strip():
            continue
        parts = line.split("\t")
        if i == 0 and parts[0] == "problem":
            continue
        parts += [""] * (len(QUEUE_COLS) - len(parts))
        rows.append(dict(zip(QUEUE_COLS, parts[: len(QUEUE_COLS)])))
    return rows


def _write_rows(rows: list[dict]) -> None:
    p = queue_path()
    tmp = p.with_suffix(p.suffix + f".tmp.{os.getpid()}")
    body = ["\t".join(QUEUE_COLS)]
    body += ["\t".join((r.get(c) or "").replace("\t", " ").replace("\n", " ")
                       for c in QUEUE_COLS) for r in rows]
    tmp.write_text("\n".join(body) + "\n")
    os.replace(tmp, p)          # atomic; readers never see a partial table


def _pid_alive(pid: str) -> bool:
    try:
        os.kill(int(pid), 0)
        return True
    except (ValueError, ProcessLookupError):
        return False
    except PermissionError:
        return True


def _reap(rows: list[dict], stale_seconds: int) -> int:
    """Return abandoned `running` rows to `todo`.

    Liveness is decided by the owning PID, never by elapsed time: a Lean run
    is expected to take days, so reaping a live worker on age would hand its
    problem to a second worker and throw the first one's work away. Age is
    consulted ONLY for rows we cannot check -- no pid recorded, or a
    timestamp we cannot parse.
    """
    import datetime
    n, now = 0, datetime.datetime.now(datetime.timezone.utc)
    for r in rows:
        if r["status"] != "running":
            continue
        if r["pid"]:
            if _pid_alive(r["pid"]):
                continue                      # working; hands off
            why = "dead owner"
        else:
            try:
                age = (now - datetime.datetime.fromisoformat(
                    r["claimed_at"])).total_seconds()
            except ValueError:
                age = float("inf")
            if age <= stale_seconds:
                continue
            why = "no pid, stale"
        r.update(status="todo", owner="", pid="", claimed_at="",
                 note=f"reaped ({why})")
        n += 1
    return n


def cmd_queue_init(args) -> int:
    man = load_manifest()
    names = sorted(man)
    if args.year:
        names = [n for n in names if man[n]["year"] == args.year]
    if args.tag:
        names = [n for n in names if args.tag in man[n]["tags"]]
    if args.variant == "full":
        names = [n for n in names if man[n]["has_solution"]]
    if args.sample:
        import random
        rng = random.Random(args.seed)
        names = sorted(rng.sample(names, min(args.sample, len(names))))

    with _Lock():
        existing = {(r["problem"], r["variant"]): r for r in _read_rows()}
        rows, added = [], 0
        for n in names:
            key = (n, args.variant)
            if key in existing:
                rows.append(existing.pop(key))
                continue
            rows.append({"problem": n, "variant": args.variant,
                         "status": "todo", "owner": "", "pid": "",
                         "claimed_at": "", "finished_at": "", "steps": "",
                         "note": ""})
            added += 1
        if args.keep_others:
            rows += list(existing.values())
        rows.sort(key=lambda r: (r["problem"], r["variant"]))
        _write_rows(rows)
    print(f"queue {queue_path()}: {len(rows)} rows ({added} new)")
    return 0


def cmd_claim(args) -> int:
    """Atomically take one todo row. Prints `problem<TAB>variant`, or
    nothing with rc=1 when the queue is drained."""
    with _Lock():
        rows = _read_rows()
        if not rows:
            sys.exit("queue is empty - run `pb.py queue-init` first")
        _reap(rows, args.stale_seconds)
        pick = None
        for r in rows:
            if r["status"] != "todo":
                continue
            if args.variant and r["variant"] != args.variant:
                continue
            if args.problem and r["problem"] != args.problem:
                continue
            pick = r
            break
        if pick is None:
            _write_rows(rows)
            return 1
        pick.update(status="running", owner=args.owner,
                    pid=str(args.pid or os.getpid()), claimed_at=_now(),
                    finished_at="", steps="", note="")
        _write_rows(rows)
    print(f"{pick['problem']}\t{pick['variant']}")
    return 0


def cmd_release(args) -> int:
    if args.status not in STATUSES:
        sys.exit(f"bad status {args.status!r}; one of {sorted(STATUSES)}")
    with _Lock():
        rows = _read_rows()
        for r in rows:
            if r["problem"] == args.problem and (
                    not args.variant or r["variant"] == args.variant):
                r.update(status=args.status, finished_at=_now(),
                         steps=str(args.steps or ""), note=args.note or "",
                         pid="")
                break
        else:
            sys.exit(f"{args.problem} not in queue")
        _write_rows(rows)
    print(f"{args.problem} -> {args.status}")
    return 0


def cmd_reap(args) -> int:
    with _Lock():
        rows = _read_rows()
        n = _reap(rows, args.stale_seconds)
        _write_rows(rows)
    print(f"reaped {n} stale claim(s)")
    return 0


def cmd_requeue(args) -> int:
    """Put terminal rows back to `todo` for another attempt.

    `claim` only ever takes `todo`, so a failed problem is never retried
    automatically -- a fleet would otherwise spend days re-attempting the
    same wall. Retrying is therefore an explicit act: this is what turns a
    pass@1 sweep into pass@2.
    """
    if "solved" in args.status and not args.force:
        sys.exit("refusing to requeue solved rows without --force")
    with _Lock():
        rows = _read_rows()
        n = 0
        for r in rows:
            if r["status"] not in args.status:
                continue
            if args.problem and r["problem"] != args.problem:
                continue
            if args.variant and r["variant"] != args.variant:
                continue
            prev = r["status"]
            r.update(status="todo", owner="", pid="", claimed_at="",
                     finished_at="", steps="",
                     note=f"requeued from {prev}"
                          + (f" ({r['note'][:40]})" if r["note"] else ""))
            n += 1
        _write_rows(rows)
    print(f"requeued {n} row(s) -> todo")
    return 0


def cmd_queue_status(args) -> int:
    with _Lock(shared=True):
        rows = _read_rows()
    by = collections_counter(r["status"] for r in rows)
    total = len(rows)
    done = by.get("solved", 0)
    print(f"{queue_path()}  {total} problems")
    for s in ["solved", "failed", "timeout", "disproved", "running", "todo",
              "skip"]:
        if by.get(s):
            print(f"  {s:8s} {by[s]:5d}")
    attempted = by.get("solved", 0) + by.get("failed", 0) + by.get("timeout", 0)
    if attempted:
        print(f"  solve rate: {done}/{attempted} attempted "
              f"= {100.0 * done / attempted:.1f}%")
    if args.verbose:
        print()
        for r in rows:
            if args.status and r["status"] != args.status:
                continue
            print(f"  {r['problem']:22s} {r['variant']:10s} {r['status']:8s} "
                  f"{r['owner']:20s} {r['note'][:40]}")
    return 0


def collections_counter(it):
    import collections
    return collections.Counter(it)


# --------------------------------------------------------------------------
# selftest
# --------------------------------------------------------------------------

SELFTEST_STMT = """import Mathlib

/-- Self-test: a stand-in for a Putnam statement. -/
theorem pb_selftest (n : ℕ) (h : 2 ≤ n) : 1 < n :=
"""

SELFTEST_CASES = [
    ("pristine stub", SELFTEST_STMT + "sorry\n", False, "a 'sorry' remains"),
    ("real proof", SELFTEST_STMT + "by omega\n", True, None),
    ("weakened statement",
     SELFTEST_STMT.replace("2 ≤ n) : 1 < n", "3 ≤ n) : 1 < n") + "by omega\n",
     False, "statement was altered"),
    ("frozen signature hidden in a comment",
     "import Mathlib\n\n-- theorem pb_selftest (n : ℕ) (h : 2 ≤ n) : 1 < n :=\n"
     "theorem pb_selftest (n : ℕ) (h : 3 ≤ n) : 1 < n :=\nby omega\n",
     False, "statement was altered"),
    ("axiom escape hatch",
     "import Mathlib\n\naxiom cheat : ∀ n : ℕ, 1 < n\n\n"
     + SELFTEST_STMT + "cheat n\n",
     False, "forbidden escape hatch"),
]


def cmd_selftest(args) -> int:
    import tempfile
    from types import SimpleNamespace

    tmp = Path(tempfile.mkdtemp(prefix="pb_selftest_"))
    man_path = tmp / "manifest.json"
    entry = {
        "name": "pb_selftest", "year": None, "index": None, "tags": [],
        "informal_statement": "", "informal_solution": "None.",
        "has_solution": False, "solution_name": None, "solution_type": None,
        "solution_sig": None, "reference_answer": None,
        "sig": extract_theorem_sig(SELFTEST_STMT + "sorry\n", "pb_selftest"),
        "sig_wsolution": extract_theorem_sig(SELFTEST_STMT + "sorry\n",
                                             "pb_selftest"),
        "src_sha256": "",
    }
    man_path.write_text(json.dumps({"pb_selftest": entry}))
    os.environ["PB_MANIFEST"] = str(man_path)

    bench = tmp / "bench"
    bench.mkdir()
    (bench / ".pb.json").write_text(
        json.dumps({"problem": "pb_selftest", "variant": "wsolution"}))

    ok = True
    for label, content, want_pass, want_msg in SELFTEST_CASES:
        (bench / "pb_selftest.lean").write_text(content)
        rc = cmd_verify(SimpleNamespace(bench=str(bench)))
        got_pass = (rc == 0)
        good = got_pass == want_pass
        print(f"  {'ok  ' if good else 'BAD '} {label}: "
              f"{'PASS' if got_pass else 'FAIL'} (expected "
              f"{'PASS' if want_pass else 'FAIL: ' + want_msg})")
        ok &= good

    shutil.rmtree(tmp, ignore_errors=True)
    print("selftest:", "OK" if ok else "FAILED")
    return 0 if ok else 1


# --------------------------------------------------------------------------

def main() -> int:
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = p.add_subparsers(dest="cmd", required=True)

    sub.add_parser("prepare").set_defaults(fn=cmd_prepare)

    pl = sub.add_parser("list")
    pl.add_argument("--year", type=int)
    pl.add_argument("--tag")
    pl.add_argument("--with-answer", action="store_true",
                    help="only problems with a factored answer")
    pl.add_argument("--no-answer", action="store_true")
    pl.add_argument("-v", "--verbose", action="store_true")
    pl.set_defaults(fn=cmd_list)

    ps = sub.add_parser("show")
    ps.add_argument("problem")
    ps.set_defaults(fn=cmd_show)

    pt = sub.add_parser("stage")
    pt.add_argument("problem")
    pt.add_argument("--dest", required=True)
    pt.add_argument("--variant", choices=["wsolution", "full"],
                    default="wsolution")
    pt.add_argument("--force", action="store_true")
    pt.set_defaults(fn=cmd_stage)

    pv = sub.add_parser("verify")
    pv.add_argument("--bench", required=True)
    pv.set_defaults(fn=cmd_verify)

    sub.add_parser("selftest").set_defaults(fn=cmd_selftest)

    qi = sub.add_parser("queue-init", help="create/extend problems.tsv")
    qi.add_argument("--variant", choices=["wsolution", "full"],
                    default="wsolution")
    qi.add_argument("--year", type=int)
    qi.add_argument("--tag")
    qi.add_argument("--sample", type=int, help="random subset of this size")
    qi.add_argument("--seed", type=int, default=0)
    qi.add_argument("--keep-others", action="store_true",
                    help="keep rows that don't match the filters")
    qi.set_defaults(fn=cmd_queue_init)

    qc = sub.add_parser("claim", help="atomically take one todo row")
    qc.add_argument("--owner", required=True)
    qc.add_argument("--pid", type=int)
    qc.add_argument("--variant", choices=["wsolution", "full"])
    qc.add_argument("--problem", help="claim this one specifically")
    qc.add_argument("--stale-seconds", type=int, default=STALE_SECONDS)
    qc.set_defaults(fn=cmd_claim)

    qr = sub.add_parser("release")
    qr.add_argument("problem")
    qr.add_argument("--status", required=True,
                    choices=sorted(STATUSES))
    qr.add_argument("--variant")
    qr.add_argument("--steps", type=int)
    qr.add_argument("--note")
    qr.set_defaults(fn=cmd_release)

    qp = sub.add_parser("reap", help="return dead/stale claims to todo")
    qp.add_argument("--stale-seconds", type=int, default=STALE_SECONDS)
    qp.set_defaults(fn=cmd_reap)

    qq = sub.add_parser("requeue", help="put failed/timeout rows back to todo")
    qq.add_argument("--status", nargs="+", default=["failed", "timeout"],
                    choices=sorted(STATUSES))
    qq.add_argument("--problem")
    qq.add_argument("--variant")
    qq.add_argument("--force", action="store_true",
                    help="required to requeue solved rows")
    qq.set_defaults(fn=cmd_requeue)

    qs = sub.add_parser("queue-status")
    qs.add_argument("-v", "--verbose", action="store_true")
    qs.add_argument("--status")
    qs.set_defaults(fn=cmd_queue_status)

    args = p.parse_args()
    return args.fn(args)


if __name__ == "__main__":
    sys.exit(main())
